services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
      
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@123
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: estore-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment: 
      - ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
       
  identityserver:
    container_name: "identityserver"
    hostname: "identityserver"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer__Clients__0__RedirectUris__0=https://localhost:8020/signin-oidc
      - IdentityServer__Clients__0__PostLogoutRedirectUris__0=https://localhost:8020/signout-callback-oidc
      - "IdentityServer=https://identityserver:8010"
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8010
      - UseCustomLocalCert=true
    depends_on:
      - catalog.api
      - basket.api
      - discount.grpc
      - ordering.api
      - shoppinggateway
    ports:
      - "8009:8080" 
      - "8010:8010"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - "IdentityServer=https://identityserver:8010"
      - ElasticConfiguration__Url=http://elasticsearch:9200
      - UseCustomLocalCert=true
    depends_on:
      - catalogdb
      - elasticsearch
      - kibana
    ports:
      - "6000:8080"
      - "6060:8081"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc:8080
      - "IdentityServer=https://identityserver:8010"
      - MessageBroker__Host=amqp://estore-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - UseCustomLocalCert=true
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=/app/discountdb
    ports:
      - "6002:8080"
      - "6062:8081"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=Pass@123;Encrypt=False;TrustServerCertificate=True
      - "IdentityServer=https://identityserver:8010"
      - ElasticConfiguration__Url=http://elasticsearch:9200
      - MessageBroker__Host=amqp://estore-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
      - UseCustomLocalCert=true
    depends_on:
      - orderdb
      - messagebroker
      - elasticsearch
      - kibana
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  shoppinggateway:
    container_name: shoppinggateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "IdentityServer=https://identityserver:8010"
      - UseCustomLocalCert=true
    ports:
      - "8008:8080"
      - "8888:8081"
    depends_on:
      - catalog.api
      - basket.api
      - discount.grpc
      - ordering.api

  shopping.web:
    container_name: "shopping.web"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:AppGateway=https://shoppinggateway:8081"
      - "ApiSettings:IdentityServer=https://identityserver:8010"
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8021:8080"
      - "8020:8081"
    depends_on:
      - catalog.api
      - basket.api
      - discount.grpc
      - ordering.api
      - shoppinggateway
      - identityserver
    volumes:
      - ~/.aspnet/https:/https:ro